/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universityhostelmanagementsystem;

/**
 *
 * @author Altaf Hussain
 */
public class MenuForm extends javax.swing.JFrame {

    /**
     * Creates new form MenuForm
     */
    public MenuForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        button7 = new java.awt.Button();
        button8 = new java.awt.Button();
        button9 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(204, 204, 255));
        panel1.setPreferredSize(new java.awt.Dimension(1356, 768));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 0, 51));
        label1.setText("******************************************************************************************************************************************************************************");
        panel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1951, -1));

        label2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        label2.setText("*******************************************************************************************************************************************************************************");
        panel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 713, 1951, -1));

        label3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        label3.setForeground(new java.awt.Color(153, 0, 0));
        label3.setText("--------------MENU BAR-----------------");
        panel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, 34));

        button1.setBackground(new java.awt.Color(0, 204, 204));
        button1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        button1.setLabel("Hostel's Fee");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 245, 343, 50));

        button2.setBackground(new java.awt.Color(0, 204, 204));
        button2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        button2.setLabel("Room Management");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        panel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 101, 343, 57));

        button3.setBackground(new java.awt.Color(0, 204, 204));
        button3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        button3.setLabel("Student Management");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        panel1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 168, 343, 57));

        button4.setBackground(new java.awt.Color(0, 204, 255));
        button4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        button4.setLabel("Room Allotment");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        panel1.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 308, 343, 57));

        button5.setBackground(new java.awt.Color(0, 204, 204));
        button5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        button5.setLabel("Employee/Staff Management");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        panel1.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 375, -1, 59));

        button6.setBackground(new java.awt.Color(0, 204, 204));
        button6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        button6.setLabel("Duties Name");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        panel1.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 444, 343, 54));

        button7.setBackground(new java.awt.Color(0, 204, 204));
        button7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        button7.setLabel("AssignDuties");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        panel1.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 508, 343, 62));

        button8.setBackground(new java.awt.Color(0, 204, 204));
        button8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        button8.setLabel("Employee Salary");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        panel1.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 580, 343, 58));

        button9.setBackground(new java.awt.Color(0, 204, 204));
        button9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        button9.setLabel("Mess Management");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        panel1.add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 648, 343, 55));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1951, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        ManageRoom MR = new ManageRoom();
        MR.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        studentForm sf= new studentForm();
        sf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button3ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        StdHostelFeeForm Fee = new StdHostelFeeForm();
        Fee.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button1ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        Room_Allotment RA= new Room_Allotment();
        RA.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        Manage_Employee ME = new Manage_Employee();
        ME.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        DutiesNameForm DN = new DutiesNameForm();
        DN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
        AssignDutyForm AD = new AssignDutyForm();
        AD.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
        EmployeePay EP=new EmployeePay();
        EP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
        MessMenuForm MM= new MessMenuForm();
        MM.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
