/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universityhostelmanagementsystem;

import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Altaf Hussain
 */
public class studentForm extends javax.swing.JFrame {

           DefaultTableModel model;

    /**
     * Creates new form studentForm
     */
    public studentForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.model = new DefaultTableModel();
        model.addColumn("First Name");
        model.addColumn("Last Name");
        model.addColumn("Gender");
        model.addColumn("Student CNIC");
        model.addColumn("Registration No.");
        model.addColumn("Student PhoneNo.");
        model.addColumn("Home PhoneNo.");
        model.addColumn("Student DOB");
        model.addColumn("Address(City)");
        jTable1.setModel(model);
        
       
    }
    
    
    public ArrayList ListStudent(String firstName, String lastName, String gender, String CNIC, String regNo,
                                  String phoneNo, String HomephoneNo, String DOB, String Address)
     {
        ArrayList<studentData> list = new ArrayList<>() ;
        studentData Sd = new studentData(firstName, lastName, gender, CNIC, regNo,
                                          phoneNo, HomephoneNo, DOB, Address);
        list.add(Sd);
        return list;
      }
    
     public void addRow( String firstName, String lastName, String gender, String CNIC, String regNo,
                          String phoneNo, String HomephoneNo, String DOB, String Address)
    {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         ArrayList<studentData> list = ListStudent(firstName, lastName, gender, CNIC, regNo,
                                                    phoneNo, HomephoneNo, DOB, Address);
         Object rowData[] = new Object[9];
         for (int i =0 ;i < list.size(); i++)
         {
             rowData[0] = list.get(i).getfirstName();
             rowData[1] = list.get(i).getlastName();
             rowData[2] = list.get(i).getgender();
             rowData[3] = list.get(i).getCNIC();
             rowData[4] = list.get(i).getregNo();
             rowData[5] = list.get(i).getphoneNo();
             rowData[6] = list.get(i).getHomephoneNo();
             rowData[7] = list.get(i).getDOB();
             rowData[8] = list.get(i).getAddress();
             
             model.addRow(rowData);
         }
       
      }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        first_Name = new javax.swing.JTextField();
        last_Name = new javax.swing.JTextField();
        std_CNIC = new javax.swing.JTextField();
        std_regNo = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        std_phoneNo = new javax.swing.JTextField();
        home_phoneNo = new javax.swing.JTextField();
        std_DOB = new javax.swing.JTextField();
        std_Address = new javax.swing.JTextField();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        SearchField = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        AddRoom3 = new javax.swing.JButton();
        AddRoom2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel1.setBackground(new java.awt.Color(204, 204, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Student Information");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 13, 259, 38));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("DateOfBirth");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 284, 99, 22));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Address");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 313, 65, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Home Phone No. ");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 255, -1, 22));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Phone No.");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 226, 99, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Registration No.");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 200, 130, -1));
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 197, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Gender");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 140, 99, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("CNIC");
        panel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 171, 55, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Last Name");
        jLabel10.setToolTipText("");
        panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 114, 99, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("First Name");
        panel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 83, 99, -1));
        panel1.add(first_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 80, 187, -1));

        last_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_NameActionPerformed(evt);
            }
        });
        panel1.add(last_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 111, 187, -1));

        std_CNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_CNICActionPerformed(evt);
            }
        });
        panel1.add(std_CNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 168, 187, -1));
        panel1.add(std_regNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 197, 187, -1));

        jTextField17.setText("jTextField17");
        panel1.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 226, -1, 0));
        panel1.add(std_phoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 226, 187, -1));
        panel1.add(home_phoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 255, 187, -1));
        panel1.add(std_DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 284, 187, -1));
        panel1.add(std_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 313, 187, -1));

        Male.setText("Male");
        panel1.add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 70, -1));

        Female.setText("Female");
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });
        panel1.add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "First name", "Last Name", "Gender", "CNIC", "Registartion No.", "Phone No.", "Home PhoneNo.", "DOB", "Address"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 890, 162));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHOSTEL/search.png"))); // NOI18N
        jLabel12.setText("Search");
        panel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 80, 20));

        SearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchFieldKeyReleased(evt);
            }
        });
        panel1.add(SearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 197, -1));

        jButtonAdd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHOSTEL/save.png"))); // NOI18N
        jButtonAdd.setText("ADD");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        panel1.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 79, -1, -1));

        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHOSTEL/save.png"))); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        panel1.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 126, -1, -1));

        jButtonDelete.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHOSTEL/delete.png"))); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        panel1.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 176, -1, -1));
        panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));
        panel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 910, 10));
        panel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 362, 910, 10));

        AddRoom3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        AddRoom3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHOSTEL/Close all jframe.png"))); // NOI18N
        AddRoom3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddRoom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRoom3ActionPerformed(evt);
            }
        });
        panel1.add(AddRoom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 0, 70, -1));

        AddRoom2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        AddRoom2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesHOSTEL/Close all jframe.png"))); // NOI18N
        AddRoom2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddRoom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRoom2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(424, 424, 424)
                    .addComponent(AddRoom2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(425, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(277, 277, 277)
                    .addComponent(AddRoom2)
                    .addContainerGap(278, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void last_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_last_NameActionPerformed

    private void std_CNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_CNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_CNICActionPerformed

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
          String firstName = first_Name.getText();
          String lastName = last_Name.getText();
          String gender = null;
           if(Female.isSelected()){
                  gender = "Female";
            }
           else
           {
               gender = "Male";
           }
          String CNIC = std_CNIC.getText();
          String regNo = std_regNo.getText();
          String phoneNo = std_phoneNo.getText();
          String HomephoneNo = home_phoneNo.getText();
          String DOB = std_DOB.getText();
          String Address  = std_Address.getText();
                   addRow( firstName, lastName, gender, CNIC, regNo,
                            phoneNo, HomephoneNo, DOB, Address);
                       first_Name.setText("");
                       last_Name.setText("");
                       if( gender.equals("Female"))
                       {
                           Female.setSelected(true);
                       }
                       else if (gender.equals("Male"))
                       {
                            Male.setSelected(true);
                       }
                        std_CNIC.setText("");
                        std_regNo.setText("");
                        std_phoneNo.setText("");
                        home_phoneNo.setText("");
                        std_DOB.setText("");
                        std_Address.setText("");
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRowCount()==1)
        {
            model.removeRow(jTable1.getSelectedRow());
        }
        else
        {
            if(jTable1.getRowCount()==0)
            {
            JOptionPane.showMessageDialog(null,"Table is empty");
        }
        else{
           JOptionPane.showMessageDialog(null,"Please select any row!");
        }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        
          DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRowCount()==1){
          String firstName = first_Name.getText();
          String lastName = last_Name.getText();
          String gender = "Male";
           if(Male.isSelected()){
                  gender = "Female";
            };
          String CNIC = std_CNIC.getText();
          String regNo = std_regNo.getText();
          String phoneNo = std_phoneNo.getText();
          String HomephoneNo = home_phoneNo.getText();
          String DOB = std_DOB.getText();
          String Address  = std_Address.getText();
                 
        jTable1.setValueAt(firstName , jTable1.getSelectedRow(), 0);
        jTable1.setValueAt(lastName, jTable1.getSelectedRow(), 1);
        jTable1.setValueAt(gender, jTable1.getSelectedRow(), 2);
        jTable1.setValueAt(CNIC, jTable1.getSelectedRow(), 3);
        jTable1.setValueAt(regNo , jTable1.getSelectedRow(), 4);
        jTable1.setValueAt(phoneNo, jTable1.getSelectedRow(), 5);
        jTable1.setValueAt(HomephoneNo, jTable1.getSelectedRow(), 6);
        jTable1.setValueAt(DOB, jTable1.getSelectedRow(), 7);
        jTable1.setValueAt(Address, jTable1.getSelectedRow(), 8);
        
        
        JOptionPane.showMessageDialog(null,"Student List Updated Successfully");
        }
        else{
        if(jTable1.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Table is empty");
        }
        else{
            JOptionPane.showMessageDialog(null,"Please select any row!");
        }
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void SearchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchFieldKeyReleased
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String search = SearchField.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_SearchFieldKeyReleased

    private void AddRoom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRoom2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AddRoom2ActionPerformed

    private void AddRoom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRoom3ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
    }//GEN-LAST:event_AddRoom3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRoom2;
    private javax.swing.JButton AddRoom3;
    private javax.swing.JRadioButton Female;
    private javax.swing.JRadioButton Male;
    private javax.swing.JTextField SearchField;
    private javax.swing.JTextField first_Name;
    private javax.swing.JTextField home_phoneNo;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField last_Name;
    private java.awt.Panel panel1;
    private javax.swing.JTextField std_Address;
    private javax.swing.JTextField std_CNIC;
    private javax.swing.JTextField std_DOB;
    private javax.swing.JTextField std_phoneNo;
    private javax.swing.JTextField std_regNo;
    // End of variables declaration//GEN-END:variables
}
